import os
import uuid
from backend.core.models.engine import EngineBodyParams
from backend.core.models.artifacts import MeshArtifact


OUTPUT_MESH_DIR = "outputs/meshes"


def generate_body_mesh(params: EngineBodyParams) -> MeshArtifact:
    """
    ENGINE v1 (POC)
    ----------------
    Generates a deterministic placeholder mesh artifact.

    This stub exists to validate the full backend pipeline.
    Real parametric body generation (SMPL/SMPL-X) will replace this in v2.
    """

    os.makedirs(OUTPUT_MESH_DIR, exist_ok=True)

    mesh_id = _generate_deterministic_id(params)
    mesh_path = os.path.join(OUTPUT_MESH_DIR, f"{mesh_id}.obj")

    _write_placeholder_mesh(mesh_path)

    return MeshArtifact(mesh_path=mesh_path)


def _generate_deterministic_id(params: EngineBodyParams) -> str:
    """
    Deterministic ID based on engine parameters.
    Same params -> same filename.
    """
    base = (
        f"{params.engine_gender}_"
        f"{params.engine_scale:.4f}_"
        f"{params.engine_shape_vector.round(4).tolist()}"
    )
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, base))


def _write_placeholder_mesh(path: str) -> None:
    """
    Writes a minimal valid OBJ file.
    This is NOT a real body mesh.
    """

    content = [
        "# Placeholder mesh generated by ENGINE v1",
        "v 0.0 0.0 0.0",
        "v 0.0 1.0 0.0",
        "v 1.0 1.0 0.0",
        "v 1.0 0.0 0.0",
        "f 1 2 3 4",
    ]

    with open(path, "w") as f:
        f.write("\n".join(content))
